### ISSUE TITLE
Install via Package Manager not working

### ISSUE THREAD

**Issue by mackrauss** [jonschlinkert/sublime-grunt-build#2]
The instructions state that the plugin for Sublime should be available via the package manager, but that seems not to be the case.

Looking at the repository https://sublime.wbond.net/repositories.json I only see the Grunt plugin from here: https://github.com/tvooo/sublime-grunt

**Comment by jonschlinkert** [comment]
Thanks so much for the heads up, I'll get this fixed

**Comment by mackrauss** [comment]
Thanks so much! Can't wait to use grunt as my build env without telling everyone in the team how to install it by hand (via git clone).

**Comment by jonschlinkert** [comment]
no problem. and do you mind if I ask what types of things you're building? I've had a lot more experience with Grunt (and Sublime) since I first put this together. I might be able to point you to some things that have been helpful in my own projects.  (it might be tomorrow before I can get to this... but I promise I won't forget!)

**Comment by jonschlinkert** [comment]
okay, I was able to update it - and I completely re-wrote the terrible README. But you will not want to use npm to install this. However, the good news is that all you need to do is provide this link: https://github.com/jonschlinkert/sublime-grunt-build/archive/master.zip

And your team members should have no problem downloading it. (also check the folder after you extract it and make sure you didn't "extract a folder into a folder".. if you know what I mean... sometimes that prevents Sublime Text from properly identifying a package.

Last, if you have any issues with using this... let me know. I'll try to get it working for you, but honestly but hope isn't lost if we can't. There are other awesome ways to use Grunt besides this. I'll close this for now since I believe I've resolved the problem, but feel free to re-open or create a new one if you still have problems with it. thanks!

**Comment by mackrauss** [comment]
Hi Jon,

we are right now using Grunt to jshint some JS files, compile coffee script, and run SASS to create CSS files.
Gradually we want to grow what Grunt does for us into more things like concatenating and minifying.

I used the git to pull the source into the folder where Sublime has the extensions. Can now call the build process but grunt doesn't work because it is in /usr/local/bin and Sublime ignores this.

**Comment by mackrauss** [comment]
Hey,

I can run grunt if I add the following line to the grunt.sublime-build file:

"path":"/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin",

However, sass doesn't work because it doesn't see sass and ruby in the path. I installed ruby via rvm and even creating aliases to /usr/local/bin won't work. Not sure how to solve this.

Any thoughts about the path? Not sure I like my solution but it works for me right now. How would I add /usr/local/bin to the path without editing the grunt.sublime-build file?

**Comment by jonschlinkert** [comment]
Sorry for taking so long to get back on this. It sounds like it's resolved based on your last comments on the other issue? Since you work with SASS and do front-end stuff, I don't know if you need static sites for any projects, but we started a project called [assemble](http://github.com/assemble/assemble) that you might find interesting.

We also started a complimentary project called [assemble-styles](http://github.com/assemble/assemble-styles) for making it easy to maintain libraries of UI components (LESS/SASS etc). We don't have any SASS examples in the project, but I would welcome pull requests for them if you found it interesting. (I'm on the core team for LESS so I won't be adding them personally lol)
